### ISSUE TITLE
`st2api not listening` regression

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#202]
See the builds where `st2api` failed (service is dead): 
1.)  https://circleci.com/gh/StackStorm/st2/801
* [st2api.log](https://circle-artifacts.com/gh/StackStorm/st2/801/artifacts/0/home/ubuntu/packages/wheezy/log/st2/st2api.log) (wheezy)
* [st2api.log](https://circle-artifacts.com/gh/StackStorm/st2/801/artifacts/0/home/ubuntu/packages/jessie/log/st2/st2api.log ) (jessie)

2.) https://circleci.com/gh/StackStorm/st2-packages/501
* [st2api.log](https://circle-artifacts.com/gh/StackStorm/st2-packages/501/artifacts/0/home/ubuntu/packages/wheezy/log/st2/st2api.log) (wheezy)

In all cases our famous error (from https://github.com/StackStorm/st2-packages/issues/106):
```py
2016-03-01 17:57:26,831 27696976 ERROR base [-] Conflict while trying to save in DB.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/persistence/base.py", line 155, in add_or_update
    model_object = cls._get_impl().add_or_update(model_object)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/models/db/__init__.py", line 174, in add_or_update
    instance.save()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/mongoengine/document.py", line 286, in save
    raise NotUniqueError(message % unicode(err))
NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error index: st2.trigger_type_d_b.$uid_1  dup key: { : "trigger_type:core:st2.generic.actiontrigger" })
2016-03-01 17:57:26,834 27696976 ERROR triggers [-] Failed registering internal trigger: {'payload_schema': {'type': 'object', 'properties': {'status': {}, 'start_timestamp': {}, 'parameters': {}, 'action_name': {}, 'result': {}, 'execution_id': {}}}, 'description': 'Trigger encapsulating the completion of an action execution.', 'name': 'st2.generic.actiontrigger', 'pack': 'core'}.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/triggers.py", line 75, in register_internal_trigger_types
    trigger_definition=trigger_definition)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/triggers.py", line 34, in _register_internal_trigger_type
    trigger_type_db = create_trigger_type_db(trigger_type=trigger_definition)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/services/triggers.py", line 234, in create_trigger_type_db
    trigger_type_db = TriggerType.add_or_update(trigger_type_db)
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/persistence/base.py", line 167, in add_or_update
    model_object=model_object)
StackStormDBObjectConflictError: Tried to save duplicate unique keys (E11000 duplicate key error index: st2.trigger_type_d_b.$uid_1  dup key: { : "trigger_type:core:st2.generic.actiontrigger" })
```

The error started appearing today. It *could be* related to recent `gunicorn` changes, after merging: https://github.com/StackStorm/st2-packages/pull/192/files
The notable thing is that ^^ PR added `workers=2` for `st2api`, while `st2auth` remains with `1 worker`.

If you read entire log files with attention, there is `st2api.app app created.` message after the actual DB error. I guess that's because logging comes from 2 workers. Eg. 1 worked died, another one still alive. But the entire `st2api` service hanged down.

Considering 2 workers change and that it appears randomly, more likely it's race condition, which we fought before in https://github.com/StackStorm/st2-packages/issues/106 and @lakshmi-kannan fixed in https://github.com/StackStorm/st2/pull/2437.

See also: https://stackstorm.slack.com/archives/stackstorm/p1456852817004646

Anyway, more investigation/debugging is needed to say for sure. cc @lakshmi-kannan @Kami @manasdk, since you know the internals better.

**Comment by armab** [comment]
FYI @dennybaa more detailed insight, since you reverted `workers=1` in https://github.com/StackStorm/st2-packages/issues/209

**Comment by armab** [comment]
Yes, after several days of not seeing DB error in CircleCI builds - assume this is fixed by reverting number of `workers=1`.

**Comment by dennybaa** [comment]
@armab please keep track of the detailed gunicorn bugs issues https://stackstorm.atlassian.net/browse/STORM-2058, unfortunately this story is far from being polished yet( I don't know if it makes sense to post bugs in st2-packages or propagate them higher, since they don't get proper attention in here(

**Comment by armab** [comment]
You're talking about `pid` problem in in JIRA,
I'm talking here about `st2api not listening` regression, when service failed to start because of some race condition with `workers=2`.

I guess they're different problems.

@dennybaa Do you still see the case when api is failed to start after reverting workers to 1?

**Comment by dennybaa** [comment]
@armab starting is okay, i'm talking about gunicorn disability to be shutdown properly, not the pid problem which has been solved already. would be nice if you also keep you hand on it)

**Comment by dennybaa** [comment]
@armab we don't see it anymore, i'm +1 to close. decide...

**Comment by armab** [comment]
> we don't see it anymore

:+1:
