### ISSUE TITLE
make: *** [binary] Error 2

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#32]
From time to time still getting errors in Circle, here is an example:
https://circleci.com/gh/StackStorm/st2-packages/148

```
[package: st2actions]      Collecting st2common (from -r ./requirements.txt (line 18))
[package: st2actions]      Exception:
[package: st2actions]      Traceback (most recent call last):
[package: st2actions]        File "/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
[package: st2actions]          status = self.run(options, args)
[package: st2actions]        File "/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
[package: st2actions]          wb.build(autobuilding=True)
[package: st2actions]        File "/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/local/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
[package: st2actions]          self.requirement_set.prepare_files(self.finder)
[package: st2actions]        File "/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/local/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
[package: st2actions]          functools.partial(self._prepare_file, finder))
[package: st2actions]        File "/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/local/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
[package: st2actions]          more_reqs = handler(req_to_install)
[package: st2actions]        File "/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/local/lib/python2.7/site-packages/pip/req/req_set.py", line 491, in _prepare_file
[package: st2actions]          session=self.session)
[package: st2actions]        File "/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/local/lib/python2.7/site-packages/pip/download.py", line 814, in unpack_url
[package: st2actions]          unpack_file_url(link, location, download_dir)
[package: st2actions]        File "/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/local/lib/python2.7/site-packages/pip/download.py", line 723, in unpack_file_url
[package: st2actions]          unpack_file(from_path, location, content_type, link)
[package: st2actions]        File "/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 645, in unpack_file
[package: st2actions]          flatten=not filename.endswith('.whl')
[package: st2actions]        File "/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 535, in unzip_file
[package: st2actions]          data = zip.read(name)
[package: st2actions]        File "/usr/lib/python2.7/zipfile.py", line 935, in read
[package: st2actions]          return self.open(name, "r", pwd).read()
[package: st2actions]        File "/usr/lib/python2.7/zipfile.py", line 968, in open
[package: st2actions]          raise BadZipfile("Truncated file header")
[package: st2actions]      BadZipfile: Truncated file header
[package: st2actions]      Traceback (most recent call last):
[package: st2actions]        File "/usr/bin/dh_virtualenv", line 106, in <module>
[package: st2actions]          sys.exit(main() or 0)
[package: st2actions]        File "/usr/bin/dh_virtualenv", line 86, in main
[package: st2actions]          deploy.install_dependencies()
[package: st2actions]        File "/usr/lib/python2.7/dist-packages/dh_virtualenv/deployment.py", line 147, in install_dependencies
[package: st2actions]          subprocess.check_call(self.pip('-r', requirements_path))
[package: st2actions]        File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
[package: st2actions]          raise CalledProcessError(retcode, cmd)
[package: st2actions]      subprocess.CalledProcessError: Command '['/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/bin/python', '/tmp/st2-20151202-9-13fzc6c/st2actions/debian/st2actions/usr/share/python/st2actions/bin/pip', 'install', '--log=/tmp/tmpF90E6u', '--no-index', '--find-links=/tmp/wheelhouse', '-r', './requirements.txt']' returned non-zero exit status 2
[package: st2actions]      debian/rules:35: recipe for target 'override_dh_virtualenv' failed
[package: st2actions]      make[1]: Leaving directory '/tmp/st2-20151202-9-13fzc6c/st2actions'
[package: st2actions]      debian/rules:14: recipe for target 'binary' failed
[package: st2actions]      make[1]: *** [override_dh_virtualenv] Error 1
[package: st2actions]      make: *** [binary] Error 2
```
Retrying build without cache fixes the problem. However I'm not sure, it could be not related to cache, just re-build probably works.

Maybe you have better idea reading this error message and understanding the cause.

**Comment by dennybaa** [comment]
@armab Have you seen this recently? I think it's outdated bug)

**Comment by armab** [comment]
Yes, same here. Seems like outdated.
