### ISSUE TITLE
(action file most likely doesn't exist or contains invalid syntax): No module named cx_Oracle

### ISSUE THREAD

**Issue by jo9208** [StackStorm/st2-packages#661]
I was making a custom pack on stackstorm for a oracle instance in stackstorm

# st2 execution get 5f5904b5e6db36c03ea812db
id: 5f5904b5e6db36c03ea812db
action.ref: oracle_test.Oracledbcheck
context.user: st2admin
parameters:
  DBName: ****
  Hostname: ****
  Password: *****
  Port: '1526'
  ServiceName:****
  Username:*****
  log_level: DEBUG
status: failed (1s elapsed)
start_timestamp: Wed, 09 Sep 2020 16:37:08 UTC
end_timestamp: Wed, 09 Sep 2020 16:37:09 UTC
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 191, in run
    action = self._get_action_instance()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 244, in _get_action_instance
    raise exc_cls(msg)
ImportError: Failed to load action class from file "/opt/stackstorm/packs/oracle_test/actions/Oracledbcheck.py" (action file most likely doesn't exist or contains invalid syntax): No module named cx_Oracle

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 237, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/loader.py", line 167, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File "/opt/stackstorm/packs/oracle_test/actions/Oracledbcheck.py", line 3, in <module>
    import cx_Oracle
ImportError: No module named cx_Oracle

it has the cx_oracle installed on the machine. seems stcakstorm isnt picking it up.

Any suggestion????

**Comment by armab** [comment]
Hello,
Thanks for opening the issue.

The question you're asking is not related to this repository and deb/rpm stackstorm packages.
Github is used for reporting bugs or code contributions and development.

I'd recommend asking the question on https://forum.stackstorm.com/ or StackStorm Community Slack.
